# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='dj-stripe',
    version='2.4.0.dev0',
    description='Django + Stripe made easy',
    python_requires='==3.*,>=3.6.0',
    project_urls={
        "documentation": "https://dj-stripe.readthedocs.io/",
        "repository": "https://github.com/dj-stripe/dj-stripe"
    },
    author='Alexander Kavanaugh',
    author_email='alex@kavdev.io',
    maintainer='Jerome Leclanche',
    maintainer_email='jerome@leclan.ch',
    license='MIT',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Web Environment', 'Intended Audience :: Developers',
        'Topic :: Office/Business :: Financial',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Framework :: Django', 'Framework :: Django :: 2.2',
        'Framework :: Django :: 3.0'
    ],
    packages=[
        'djstripe', 'djstripe.contrib', 'djstripe.contrib.rest_framework',
        'djstripe.management', 'djstripe.management.commands',
        'djstripe.migrations', 'djstripe.models',
    ],
    package_data={
        "djstripe": [
            "locale/fr/LC_MESSAGES/*.po", "locale/ru/LC_MESSAGES/*.po",
            "templates/djstripe/admin/*.html"
        ],
    },
    install_requires=['django>=2.2', 'jsonfield>=3.0', 'stripe>=2.48.0'],
    extras_require={
        "dev": [
            "black==20.*,>=20.8.0.b1", "djangorestframework==3.*,>=3.11.0",
            "flake8==3.*,>=3.8.2", "isort==4.*,>=4.3.21",
            "psycopg2==2.*,>=2.8.5", "pytest==5.*,>=5.4.3",
            "pytest-django==3.*,>=3.9.0"
        ]
    },
)
